{% set name = "pretty_errors" %}
{% set version = "1.2.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70198b13b5b438fe4ccef832e0c8659249965b69ba130d1b2130b6ec74336b0b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - colorama

test:
  imports:
    - pretty_errors

about:
  home: https://github.com/onelivesleft/PrettyErrors/
  license: MIT
  license_family: MIT
  # License file manually packaged. See https://github.com/onelivesleft/PrettyErrors/pull/29
  license_file: LICENSE
  summary: Prettifies Python exception output to make it legible.

  description: |
    Prettifies Python exception output to make it legible.
  dev_url: https://github.com/onelivesleft/PrettyErrors/

extra:
  recipe-maintainers:
    - Silun
